trigger:
- master
- imx_v2018.03_4.14.98_2.0.0_ga

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt update 
  displayName: 'Update APT sources'

# Travis have this by default, because we preinstalled build-essential
- script: sudo apt install uuid-dev flex bison build-essential gcc-arm-linux-gnueabi
  displayName: 'Install VSTS dependencies'

# Configure and build U-Boot
- script: ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make mx6ull_prime_defconfig
  displayName: 'Configure U-Boot build'

# Build U-Boot
- script: ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make -j4
  displayName: 'Build U-Boot'

# Upload artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish U-Boot build artifacts'
  inputs:
    pathtoPublish: u-boot-dtb.imx
    artifactName: U-Boot
